name: Create Pull Request to Another Repository

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v3
        with:
          repository: 'nogson/takePR'
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: 'another-repo'

      - name: Create a new branch
        run: |
          cd another-repo
          git checkout -b new-feature-branch
          # ここでファイルに変更を加える
          git config user.email "your-email@example.com"
          git config user.name "Your Name"
          git add .
          git commit -m "Add new feature"
          git push origin new-feature-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: another-repo
          branch: new-feature-branch
          base: main # プルリクエストを作成する先のブランチ
          title: "Add new feature"
          body: "This PR adds a new feature."
          draft: false
