name: makePR

on: workflow_dispatch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout A's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/makePR"
          fetch-depth: 0
          ref: main
      # 他の必要なステップ（例：変更の実行）
      - name: Generate github token for GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout B's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/takePR"
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      # Bのリポジトリに対する変更をコミット
      - name: Create a new file
        run: |
          echo "Update generated at $(date)" > update-info.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add update-info.txt
          git commit -m "Automated update: $(date)"
      - name: Create Pull Request to B's repo
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Update from A"
          title: "Update from A"
          body: "This is an automated PR to update content"
          branch: "update-from-A"
