name: makePR

on: workflow_dispatch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Global Git Configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
      - name: Generate github token for GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }} 
          
      - name: Checkout makePR's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/makePR"
          fetch-depth: 0

      - name: Checkout takePR's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/takePR"
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          path: "takePR"          
      
      - name: Commit Update Info to makePR's repo
        run: |
          echo "UPDATE_INFO=Update generated at $(date)" > update-info.txt
        
      - name: Copy updated variables to takePR's repo
        run: |
          cp update-info.txt takePR/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Update from makePR"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: feat/abc
          branch-suffix: timestamp
          delete-branch: true
          title: "Update from makePR"
          body: Variables has been updated
          path: "takePR"
